#!/bin/bash

function elemento2()
{   
    RUTA_T=$(pwd)
    opcion=7
    FILEIDD=$(php /var/www/html/panel/inc/comp/parse_url.php "${FARRAY[0]}")
    [[ ! $ID_DB_PELI ]] && activarPlantilla=true
    [[ ${EXTRAER_GDRIVE} == "1080" ]] && CALIDA1="(1080)" && gooledd720 ${FILEIDD} "${EXTRAER_GDRIVE}p"
    [[ ${EXTRAER_GDRIVE} == "720" ]] && CALIDA1="(720)" && yt-dl2.sh "${FARRAY[0]}" #gooledd720 ${FILEIDD} "${EXTRAER_GDRIVE}p"
    [[ ${EXTRAER_GDRIVE} == "480" ]] && CALIDA1="(480)" && gooledd720 ${FILEIDD} "${EXTRAER_GDRIVE}p"
    [[ ${EXTRAER_GDRIVE} == "360" ]] && CALIDA1="(360)" && gooledd720 ${FILEIDD} "${EXTRAER_GDRIVE}p"
    [[ ! ${EXTRAER_GDRIVE} ]] && drived
    SAVEIFS=$IFS; 
    IFS=$(echo -en "\n\b")
    TArchivo; 
    descompri;
    aguaMarca; 
    _quitar_audio
    EscogerAudio; 
    [[ ! $ID_DB_PELI ]] && addBd;
    PegarSubtitulos; 
    renom; 
    ConvertirPeli; 
    for i in "${SERVIDORES[@]}"; do
        case $i in
            1080) subida_o_s_s_1080; IFS=$SAVEIFS; sudmenu 2>/dev/null
            ;;
            720) subida_o_s_s_720; IFS=$SAVEIFS; sudmenu 2>/dev/null
            ;;
            "720p") subida_o_s_s_720p; IFS=$SAVEIFS; sudmenu 2>/dev/null
            ;;
            "hqq.tv"|"jetload"|"uptobox"|"gounlimited"|"mega"|"gdfree"|"gdvip") SERVIDOR_A_BUSCAR="${i}"; 
            ServidorAll "$MiPeli" " " "$SERVIDOR_A_BUSCAR" "$SERVIDOR_A_BUSCAR" "$ID_DB_PELI"
            ;;
            *) echo default
            ;;
        esac
    done
    # IFS=$SAVEIFS; 
    # sudmenu 2>/dev/null
    # && rm "$MiPeli"
    cd ${RUTA_T}; rm -rf ${RUTA_T}/*
}

function elemeto1()
{
    if [[ "${FARRAY[0]}" =~ "drive.google.com" && ${EXTRAER_GDRIVE} == "720" || "${FARRAY[0]}" =~ "drive.google.com" && ${EXTRAER_GDRIVE} == "1080" || "${FARRAY[0]}" =~ "drive.google.com" && ${EXTRAER_GDRIVE} == "480" || "${FARRAY[0]}" =~ "drive.google.com" && ${EXTRAER_GDRIVE} == "360" ]];then
        FILEIDD=$(php /var/www/html/panel/inc/comp/parse_url.php "${FARRAY[0]}")
        opcion=7
        activarPlantilla=true #Activar la creacion de la plantilla en el panel web
        case "$CALIDA1" in
            1080) CALIDA1="(1080)"; 
            gooledd720 ${FILEIDD} "${EXTRAER_GDRIVE}p"; TArchivo; descompri; aguaMarca; EscogerAudio; addBd; PegarSubtitulos; SAVEIFS=$IFS; renom; ConvertirPeli; subida_o_s_s_1080; IFS=$SAVEIFS; sudmenu 2>/dev/null 
            ;;
            720) CALIDA1="(720)";
            gooledd720 "${FILEIDD}" "${EXTRAER_GDRIVE}p"; TArchivo; descompri; aguaMarca; EscogerAudio; addBd; PegarSubtitulos; SAVEIFS=$IFS; renom; ConvertirPeli; subida_o_s_s_720; IFS=$SAVEIFS; sudmenu 2>/dev/null
            ;;
            480) CALIDA1="(480)";
            gooledd720 "${FILEIDD}" "${EXTRAER_GDRIVE}p"; TArchivo; descompri; aguaMarca; EscogerAudio; addBd; PegarSubtitulos; SAVEIFS=$IFS; renom; ConvertirPeli; subida_o_s_s_720; IFS=$SAVEIFS; sudmenu 2>/dev/null
            ;;
            360) CALIDA1="(360)";
            gooledd720 "${FILEIDD}" "${EXTRAER_GDRIVE}p"; TArchivo; descompri; aguaMarca; EscogerAudio; addBd; PegarSubtitulos; SAVEIFS=$IFS; renom; ConvertirPeli; subida_o_s_s_720; IFS=$SAVEIFS; sudmenu 2>/dev/null
            ;;
            *) echo default; exit
            ;;
        esac
    fi
    
}

function elemeto2_720p()
{
    # PARAMETRO DEFINIDO PARA PODER DESCARGAR
        opcion=7
        activarPlantilla=true #Activar la creacion de la plantilla en el panel web
        case "$CALIDA1" in
            1080) CALIDA1="(1080)"; 
                drived; TArchivo; descompri; aguaMarca; EscogerAudio; addBd; PegarSubtitulos; SAVEIFS=$IFS; renom; ConvertirPeli; subida_o_s_s_1080; IFS=$SAVEIFS; sudmenu 2>/dev/null 
            ;;
            720) CALIDA1="(720)";
                drived; TArchivo; descompri; aguaMarca; EscogerAudio; addBd; PegarSubtitulos; SAVEIFS=$IFS; renom; ConvertirPeli; subida_o_s_s_720; IFS=$SAVEIFS; sudmenu 2>/dev/null
            ;;
            "720p") CALIDA1="(720)";
                drived; TArchivo; descompri; aguaMarca; EscogerAudio; addBd; PegarSubtitulos; SAVEIFS=$IFS; renom; ConvertirPeli; subida_o_s_s_720p; IFS=$SAVEIFS; sudmenu 2>/dev/null
            ;;
            "hqq.tv"|"jetload"|"uptobox"|"gounlimited") 
            SERVIDOR_A_BUSCAR=${CALIDA1}; drived; TArchivo; descompri; aguaMarca; EscogerAudio; PegarSubtitulos; SAVEIFS=$IFS; renom; ConvertirPeli; IFS=$SAVEIFS; ServidorAll "$MiPeli" " " "$SERVIDOR_A_BUSCAR" "$SERVIDOR_A_BUSCAR" "$ID_DB_PELI"
            ;;
            *) echo default; exit
            ;;
        esac
}

function Respaldo()
{
    local enlace

    echo "este es el enlace que se enviara: ${FARRAY[0]}"
    echo 
    # enlace=$(respaldoBackup "${FARRAY[0]}")
    respaldoBackup "${FARRAY[0]}" enlace
    echo "lo qque se esperesa: ${enlace}"
    agregarRespaldoBd "${ID_UNICO}" "${enlace}" "admin"
}

function obtenerLinkCalidad()
{
    local URL=$1
    local CALIDAD=$2

    FILEIDD=$(php /var/www/html/panel/inc/comp/parse_url.php "${URL}")
    gooledd720 ${FILEIDD} "${CALIDAD}"

    FILENAME=$(wget -q --show-progress -O - "https://drive.google.com/file/d/${FILEIDD}/view" | sed -n -e 's!.*<title>\(.*\)\ \-\ Google\ Drive</title>.*!\1!p')
    rclone copy "${FILENAME}" drive7:/obt_calidades -P
    rclone link drive7:/obt_calidades/"${FILENAME}"
}
function _quitar_audio()
{
    if [[ $ACTIVARAUDIO ]];then
        [[ $IDIOMA1 == "LATINO" ]] && ELEGIRAUDIO=1
        [[ $IDIOMA1 == "CASTELLANO" ]] && ELEGIRAUDIO=2
        [[ $IDIOMA1 == "SUB" ]] && ELEGIRAUDIO=3
    fi
    
}
# echo "OPTIND inicia en $OPTIND"
v=0
while getopts "c:t:n:e:i:s:a:L:F:C:I:K:" optname
  do
    case "$optname" in
        "a")
            ID_DB_PELI=$OPTARG;
            # echo "Se ha especificado la opción $optname y su valor es $CALIDA1"
            ;;
        "c")
            CALIDA1="($OPTARG)";
            # [[ $CALIDA1 == "netu" ]] && CALIDA1="hqq.tv";
            # echo "Se ha especificado la opción $optname y su valor es $CALIDA1"
            ;;
        "K")
            SERVIDORES[$v]=$OPTARG;
            ((v++))
            # echo "Se ha especificado la opción $optname y su valor es $CALIDA1"
            ;;
        "C")
            EXTRAER_GDRIVE=$OPTARG;
            # echo "Se ha especificado la opción $optname y su valor es $CALIDA1"
            ;;
        "I")
            ID_UNICO=${OPTARG}; ID_DB_PELI=$OPTARG;
            # echo "Se ha especificado la opción $optname y su valor es $CALIDA1"
            ;;
        "e")
            FARRAY[0]=$OPTARG
            # echo "La opción $optname tiene el valor ${FARRAY[0]}"
            ;;
        "n")
            nameori=${OPTARG^^}
            # echo "La opción $optname tiene el valor $nameori"
            ;;
        "t")
            IDPELICULA=$OPTARG
            # echo "La opción $optname tiene el valor $IDPELICULA"
            ;;
        "i")
            IDIOMA1=${OPTARG^^}
            [[ $IDIOMA1 == "INGLES" ]] && IDIOMA1="SUB";
            # echo "La opción $optname tiene el valor $IDIOMA1"
            ;;
        "s")
            if [[ $OPTARG == "mkv" ]];then
                EXTRASUB=true
            else
                LSUB="${OPTARG}"
                CSUB=1
            fi
            # echo "La opción $optname tiene el valor $IDIOMA1"
            ;;
        "L")
            ACTIVARAUDIO=$OPTARG
            ;;
        "F")
            ELIMINARSUB=$OPTARG
        ;;
        "?")
            echo "Opción desconocida $OPTARG"
            ;;
        ":")
            echo "Sin valor de argumentos para la opción $OPTARG"
            ;;
        *)
        # Should not occur
            echo "Error desconocido mientras se procesaban las opciones"
            ;;
        esac
        # echo "OPTIND ahora es $OPTIND"
        # echo "----VUELTA # $v -------"
        
done

case ${SERVIDORES[0]} in
    "hqq.tv"|"jetload"|"uptobox"|"gounlimited"|"mega"|"gdfree"|"gdvip"|1080|720|720p) elemento2
    ;;
    "respaldo") Respaldo
    ;;
    "obt_1080") CALIDAD="1080p"; obtenerLinkCalidad ${FARRAY[0]} $CALIDAD
    ;;
    *) echo default
    ;;
esac

# case ${EXTRAER_GDRIVE} in
#     "extra_720") elemeto1
#     ;;
#     "respaldo") Respaldo
#     ;;
#     "obt_1080") CALIDAD="1080p"; obtenerLinkCalidad ${FARRAY[0]} $CALIDAD
#     ;;
#     "todo_720") elemeto2_720p
#     ;;
#     *) elemeto1
#     ;;
# esac
exit


