#!/bin/bash
# IKEY6=/var/local/Key6.txt
# PSW6=$(cat $IKEY6)
source /usr/local/bin/config.ini

# extract the protocol
proto="$(echo $1 | grep :// | sed -e's,^\(.*://\).*,\1,g')"
# remove the protocol
url="$(echo ${1/$proto/})"
# extract the user (if any)
user="$(echo $url | grep @ | cut -d@ -f1)"
# extract the host and port
hostport="$(echo ${url/$user@/} | cut -d/ -f1)"
# by request host without port    
host="$(echo $hostport | sed -e 's,:.*,,g')"
# by request - try to extract the port
port="$(echo $hostport | sed -e 's,^.*:,:,g' -e 's,.*:\([0-9]*\).*,\1,g' -e 's,[^0-9],,g')"
# extract the path (if any)
path="$(echo $url | grep / | cut -d/ -f2-)"

function GoogleDriveDescarga()
{
    FILEID=$1
    # FILEID="$(echo $FILEID | sed -n 's#.*\https\:\/\/drive\.google\.com/file/d/\([^.]*\)\/view.*#\1#;p')";
    # FILEID="$(echo $FILEID | sed -n 's#.*\https\:\/\/drive\.google\.com/file/d/\([^.]*\)\/view.*#\1#;p')";
    # FILENAME="$(wget -q --show-progress -O - "https://drive.google.com/file/d/$FILEID/view" | sed -n -e 's!.*<title>\(.*\)\ \-\ Dysk\ Google</title>.*!\1!p')";
    FILENAME="$(wget -q --show-progress -O - "https://drive.google.com/file/d/$FILEID/view" | sed -n -e 's!.*<title>\(.*\)\ \-\ Google\ Drive</title>.*!\1!p')";
    FILENAME1=$(echo "$FILENAME")
    wget -q --show-progress --save-cookies /tmp/cookies.txt --no-check-certificate "https://docs.google.com/uc?export=download&id=$FILEID" -O $FILENAME

    FILENAME2=$(echo "$FILENAME" | awk '{print $1}')
    msg()
    {
    BRAN='\033[1;37m' && VERMELHO='\e[31m' && VERDE='\e[32m' && AMARELO='\e[33m'
    AZUL='\e[34m' && MAGENTA='\e[35m' && MAG='\033[1;36m' && NEGRITO='\e[1m' && SEMCOR='\e[0m'
    case $1 in
    -ne)cor="${VERMELHO}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}";;
    -pur)cor="${MAGENTA}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
    -ama)cor="${AMARELO}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
    -verm)cor="${AMARELO}${NEGRITO}[!] ${VERMELHO}" && echo -e "${cor}${2}${SEMCOR}";;
    -azu)cor="${MAG}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
    -verd)cor="${VERDE}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
    -red)cor="${VERMELHO}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
    -bla)cor="${BRAN}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}";;
    -bar2)cor="${AZUL}${NEGRITO}======================================================" && echo -e "${cor}${SEMCOR}";;
    -bar)cor="${AZUL}${NEGRITO}========================================" && echo -e "${cor}${SEMCOR}";;
    esac
    }
    function ProgressBar(){
    chars="/-\|" 
    while :; do 
        for (( i=0; i<${#chars}; i++ )); do
        sleep 0.1
        printf " "; echo -en "${chars:$i:1}" "\r"
        done 
    done & trap 'kill $!' SIGTERM SIGKILL

    }
    function compro(){

        if grep -q "Quota exceeded" "$FILENAME2"; then
                rm "$FILENAME" && \
                echo -e "\033[1;31mEnlace descargado demaciadas veces (Quota Exceeded)\033[0m" && \
                echo "https://drive.google.com/file/d/$FILEID/view"
                echo -e "\033[1;33mFile \033[1;31m$FILENAME\033[0m \033[1;33mNO se puede DESCARGAR\033[0m" 
                echo -e "\n"
                echo -e "\n"
                msg -ama "GENERANDO NUEVO ENLACE..."

                RD1=$(pwd)
                cd $RCOPY2 && drive copy -id "$FILEID" ${NAMEBINDERCOPY}; sleep 6s
                drive pub ${NAMEBINDERCOPY}/"${FILENAME}"
                newlink=$(drive pub ${NAMEBINDERCOPY}/"${FILENAME}" | awk  -F "published on" '{print $2}')
                newlinkID=$(echo $newlink | awk -F "=" '{print $2}')
                FILEID=${newlinkID}
                cd $RD1
                ProgressBar
                msg -ama "Por favor, espere..."
                sleep 7s
                kill $!
                FILENAME=$(wget -q --show-progress -O - "https://drive.google.com/file/d/$FILEID/view" | sed -n -e 's!.*<title>\(.*\)\ \-\ Google\ Drive</title>.*!\1!p')
                FILENAME1=$(echo "$FILENAME")
                wget -q --show-progress --save-cookies /tmp/cookies.txt --no-check-certificate "https://docs.google.com/uc?export=download&id=$FILEID" -O $FILENAME

                FILENAME2=$(echo "$FILENAME" | awk '{print $1}')

                    if grep -q "Quota exceeded" "$FILENAME2"; then
                        rm "$FILENAME" && \
                        echo -e "\033[1;31mEnlace descargado demaciadas veces (Quota Exceeded)\033[0m" && \
                        echo "https://drive.google.com/file/d/$FILEID/view"
                        echo -e "\033[1;33mFile \033[1;31m$FILENAME\033[0m \033[1;33mNO se puede DESCARGAR\033[0m" 
                        else
                            echo -e "\033[1;33mFile \033[1;36m$FILENAME1\033[0m \033[1;33mONLINE\033[0m"
                            sleep 2
                            rm "$FILENAME" 2>/dev/null
                            rm "$FILENAME2" 2>/dev/null
                            # ONLINE=$(echo "$FILENAME")
                            # ENLACESVIVOS[$i]=$(echo "$FILEID")
                    fi

            else

                echo -e "\033[1;33mFile \033[1;36m$FILENAME1\033[0m \033[1;33mONLINE\033[0m"
                rm "$FILENAME2" && \
                ONLINE=$(echo "$FILENAME")
                ENLACESVIVOS=$(echo "$FILEID")
            fi
    }

    function newEnlace(){

        msg -ama "GENERANDO NUEVO ENLACE..."

        RD1=$(pwd)
        cd $RCOPY2 && drive copy -id "$FILEID" ${NAMEBINDERCOPY}; sleep 6s
        drive pub ${NAMEBINDERCOPY}/"$FILENAME"
        newlink=$(drive pub ${NAMEBINDERCOPY}/"$FILENAME" | awk  -F "published on" '{print $2}')
        newlinkID=$(echo $newlink | awk -F "=" '{print $2}')
        FILEID=${newlinkID}
        cd $RD1
        ProgressBar
        msg -ama "Por favor, espere..."
        sleep 5s
        kill $!

    }


    function googleDescarga () {


    # wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget -q --show-progress --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate "https://docs.google.com/uc?export=download&id=$FILEID" -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=$FILEID" -c -O "$FILENAME" && rm -rf /tmp/cookies.txt;
    # echo "file $FILENAME has been downloaded"
    CONFIRM_CODE=$(wget -q --show-progress --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate "https://docs.google.com/uc?export=download&id=$FILEID" -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')
    wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$CONFIRM_CODE&id=$FILEID" -c -O "$FILENAME" && rm -rf /tmp/cookies.txt;
    error=$?
    echo $error
    NAMEFILEE=$(msg -verd "$FILENAME")
    echo "file $NAMEFILEE DESCARGADO"

    }

    function CompVideo(){

        extv="$1"; ext=${extv##*.}
        case $ext in
            mkv ) EXTVIDEO="mkv";;
            mp4 ) EXTVIDEO="mp4";;
            avi ) EXTVIDEO="avi";;
            mpg ) EXTVIDEO="mpg";;
            *) msg -azu "NO ES UN VIDEO";;
        esac

        if [[ $ext = $EXTVIDEO && -f "$FILENAME" ]]; then

            ORIFILENAME=${extv}
            mv -- "${extv}" "${extv//['][!”#$%&’()*+,/ :;<=>?@\^_`{\|}~-']/_}";
            extv=${extv//['][!”#$%&’()*+,/ :;<=>?@\^_`{\|}~-']/_}
            vi=$(ffprobe "$extv" 2>&1 | grep -i "stream" | wc -l)
            if [[ $vi -le 1 ]]; then
                until [[ $vi -ge 2 ]]; do
                    msg -red "ARCHIVO $FILENAME DAÑADO"
                    msg -ama "REINTANTANDO DESCARGA..."
                    sleep 8
                    rm -rf "$FILENAME"
                    googleDescarga
                    mv -- "${ORIFILENAME}" "${ORIFILENAME//['][!”#$%&’()*+,/ :;<=>?@\^_`{\|}~-']/_}";
                    extv=${ORIFILENAME//['][!”#$%&’()*+,/ :;<=>?@\^_`{\|}~-']/_}
                    vi=$(ffprobe "$extv" 2>&1 | grep -i "stream" | wc -l)
                done

            else
                msg -ama "$ORIFILENAME SALUDABLE"
            fi
            mv -- "${extv}" "$ORIFILENAME"
        elif [[ $ext = "rar" ]]; then

                unrar t -p$PSW6 $1
                err=$?
                echo $err
                numerr='[1-2]'
                if [[ $err = $numerr ]]; then
                    while :; do
                        msg -ama "RAR DAÑADO. REITENTANDO..."
                        rm -rf "$FILENAME"
                        googleDescarga
                        unrar t -p$PSW6 "$FILENAME"
                        err=$?
                        if [[ $err != $numerr ]]; then
                            break
                        fi
                    done
                fi
        fi

    }

    function drivego(){

        msg -pur "DESCARGANDO CARPETA"
        compro
        s=$(pwd)
        s1=$(pwd | cut -d "/" -f7)
        cd /root/.gd1/$s1 && echo | drive pull -id $FILEID
        
        err=$?
        if [[ $err != 0 ]]; then
            compro; googleDescarga; CompVideo "$FILENAME"
        fi
        find . -type f \( -name "*.mp4" -o -name "*.mkv" -o -name "*.avi" -o -name "*.mpg" \) -exec mv {} $s 2>/dev/null \;
        cd $s
        # mv -- * "$s" && cd $s
    }




    compro
    googleDescarga
    echo "$FILENAME"

    sta=$(stat -c %s "$FILENAME")
    if [[ -d "$FILENAME" || $sta -eq 0 ]]; then
        drivego
        unset FILENAME
    fi



    if [[ ${FILENAME##*.} != "srt" && -f "$FILENAME" ]]; then
        pesodelarchi=$(stat -c %s "$FILENAME" | wc -L)
        echo "ES UN FICHEROOOOO"
    fi

    e=1
    if [[ $FILENAME && -f "$FILENAME" ]]; then

    until [[ $pesodelarchi -ge 5 ]]; do
        sleep 5
        rm -rf "$FILENAME"
        googleDescarga
        msg -ama "Reintentando..."
        pesodelarchi=$(stat -c %s "$FILENAME" | wc -L)
        if [[ $e -eq 10 ]]; then
            break
        fi
        if [[ $e -eq 3 ]]; then
            newEnlace; googleDescarga
            # drivego
            pesodelarchi=$(stat -c %s "$FILENAME" | wc -L)
        fi
        let e=$e+1
    done
    fi


    if [[ $error = 0 ]]; then
        CompVideo "$FILENAME"
    fi

    RD1=$(pwd)
    cd $RCOPY2 && drive unpub -id "${FILEID}" 2>/dev/null
    cd $RD1
}


if [[ $host == "drive.google.com" || $host == "docs.drive.com" ]]; then
    id=$(php /var/www/html/panel/inc/comp/parse_url.php "${1}")
    GoogleDriveDescarga $id
elif [[ $host == "www.mediafire.com" ]]; then
    deUniversal $1
fi