#!/bin/bash
FILE_ID=${1}
BUSSCAR_CALIDAD=${2}
log_aria=".logAria"
cookyes=".cookies.txt"
terminar="(OK):download completed"
error1="(ERR):error occurred."
salida2="salida2"
[[ -e $log_aria ]] && rm -rf $log_aria
[[ -e $cookyes ]] && rm -rf $cookyes
[[ -e $salida2 ]] && rm -rf $salida2
[[ -e `ls *.mp4 *.mkv *.avi *.mpg 2>/dev/null` ]] && rm *.mp4 *.mkv *.avi *.mpg 2>/dev/null

wget -q --show-progress --save-cookies .cookies.txt --keep-session-cookies --no-check-certificate "https://drive.google.com/get_video_info?docid=${FILE_ID}" -O salida2

FILENAME=$(wget -q --show-progress -O - "https://drive.google.com/file/d/${FILE_ID}/view" | sed -n -e 's!.*<title>\(.*\)\ \-\ Google\ Drive</title>.*!\1!p')

echo " " > $log_aria
texto=$(cat salida2);
url=$(/usr/local/bin/php/apis/./api.php "${texto}" "${BUSSCAR_CALIDAD}");
i=1
if [[ $url != false ]];then
    while true 
    do
        # aria2c -x16 -s16 --load-cookies .cookies.txt -c "${url}" -o "${FILENAME}"
        aria2c -x16 -s16 --load-cookies .cookies.txt -c "${url}" -o "${FILENAME}" > ${log_aria} &
        # aria2c -x16 -s16 --load-cookies .cookies.txt -c "${url}" -o "${FILENAME}" 2>&1 | tee ${log_aria} &
        jobs -l
        sleep 5
        kill %"${i}"
        echo "VUELTA # $i"
        echo "--------------"
        cat $log_aria
        
        if fgrep "$terminar" $log_aria ;then
            break
        elif fgrep "$error1" $log_aria ;then
            break
        fi
        ((i++))
    done
    # find [path] -type f -not -name "${FILENAME}" -not -name 'backup.tar.gz' -delete
    # find . -type f -not -name "${FILENAME}" -print0 | xargs -0 rm --
    exit 0
else
    echo "NO EXISTE LA URL"
    echo $url
    # exit
fi


